name: Приветствие новичков

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        issue-message: |
          👋 Привет! Мы скоро проверим твою задачу.
          Если нужно уточнить детали — мы напишем.
          ⭐️ Поставь звёздочку проекту
          С уважением,
          Команда «Автосалон» 🚗
        
        pr-message: |
          🚀 Спасибо за первый Pull Request!
          Мы проверим твой код в ближайшее время.
          Если нужны правки — мы напишем в комментариях.
          ⭐️ Поставь звёздочку проекту!
          
        
